### ISSUE TITLE
NancyHal Organisation

### ISSUE THREAD

**Issue by robert-ovens** [NancyHal/Nancy.Hal#31]
Hi all and in particular to @danbarua , the creator of Nancy.Hal.

I'd like to suggest that we create an Github Organisation for Nancy.Hal. It is essentially a convenience for manging both the code and the CI assets. We can grant access for all organisation members to the circleci assets. It also means that sensitive items such as nuget keys can be moved into the ci pipeline (where it can only be viewed by organisation members) rather than being part of the repo where everyone can see them.

What is the consensus?

**Comment by drewfreyling** [comment]
@danbarua are we able to get this project moved to https://github/NancyHal organisation? That way we can get the CI build going for https://github.com/danbarua/Nancy.Hal/pull/32 so we can have .net standard 1.6 support.

**Comment by danbarua** [comment]
Hi,

This has been done!
